
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 22 07:55:57 CET 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 20;
  public static final int RIGHT_BRACKET = 39;
  public static final int CONST = 11;
  public static final int CASE = 7;
  public static final int INTEGER = 24;
  public static final int ARRAY = 4;
  public static final int FOR = 19;
  public static final int CHARACTER = 8;
  public static final int NOT = 32;
  public static final int AND = 3;
  public static final int LT = 28;
  public static final int RECORD = 38;
  public static final int TYPE = 45;
  public static final int OR = 34;
  public static final int NUMERIC_INTEGER_CONST = 49;
  public static final int COMMA = 10;
  public static final int DOUBLE_DOT = 15;
  public static final int DIV = 12;
  public static final int BEGIN = 6;
  public static final int RIGHT_PARENTHESIS = 40;
  public static final int GEQ = 21;
  public static final int ASSIGN = 5;
  public static final int IF = 23;
  public static final int DOT = 14;
  public static final int OF = 33;
  public static final int EOF = 0;
  public static final int PROGRAM = 36;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int ADD = 2;
  public static final int MOD = 29;
  public static final int NEQ = 31;
  public static final int EQ = 18;
  public static final int REAL = 37;
  public static final int COLONS = 9;
  public static final int ELSE = 16;
  public static final int NUMERIC_REAL_CONST = 50;
  public static final int TO = 44;
  public static final int WHILE = 47;
  public static final int THEN = 43;
  public static final int LEQ = 27;
  public static final int END = 17;
  public static final int STRING_CONST = 51;
  public static final int GT = 22;
  public static final int SUB = 42;
  public static final int LEFT_BRACKET = 25;
  public static final int VAR = 46;
  public static final int PROCEDURE = 35;
  public static final int LEFT_PARENTHESIS = 26;
  public static final int DO = 13;
  public static final int IDENTIFIER = 48;
  public static final int SEMI_COLONS = 41;
}

